services:
  - type: web
    name: crud
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
