import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Platform, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { getAdminChat, getChatMessages, getChatUsers, sendChatMessage } from '../services/api';

export default function ChatScreen({ token, user, onError }) {
  const [users, setUsers] = useState([]), [query, setQuery] = useState(''), [active, setActive] = useState(null);
  const [messages, setMessages] = useState([]), [text, setText] = useState(''), [loading, setLoading] = useState(false);
  useEffect(() => { getChatUsers(token, query).then(setUsers).catch(onError); }, [query, token]);
  async function openChat(person) { setActive(person); setLoading(true); try { setMessages((await getChatMessages(person.id, token)).messages); } catch (e) { onError(e); } finally { setLoading(false); } }
  useEffect(() => { if (!active) return; const id = setInterval(() => getChatMessages(active.id, token).then(d => setMessages(d.messages)).catch(() => {}), 5000); return () => clearInterval(id); }, [active, token]);
  async function submit() { if (!text.trim() || !active) return; const value = text.trim(); setText(''); try { const m = await sendChatMessage(active.id, value, token); setMessages(current => [...current, m]); } catch (e) { setText(value); onError(e); } }
  if (active) return <KeyboardAvoidingView className="flex-1 bg-canvas" behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View className="flex-row items-center border-b border-line px-6 py-5"><TouchableOpacity onPress={() => setActive(null)}><Text className="mr-4 text-2xl text-brand">‹</Text></TouchableOpacity><View><Text className="text-xl font-extrabold text-ink">{active.name}</Text><Text className="text-xs text-[#47B8A5]">● Online</Text></View></View>{loading ? <ActivityIndicator className="mt-8" color="#6750E8" /> : <FlatList className="flex-1 px-5" data={messages} keyExtractor={item => item._id} renderItem={({ item }) => <View className={`my-1 max-w-[82%] rounded-2xl px-4 py-3 ${String(item.sender) === String(user.id) ? 'self-end bg-brand' : 'self-start bg-surface border border-line'}`}><Text className={String(item.sender) === String(user.id) ? 'text-white' : 'text-ink'}>{item.text}</Text></View>} contentContainerStyle={{ paddingVertical: 16 }} /> }<View className="flex-row items-center border-t border-line bg-canvas px-4 py-3"><TextInput className="mr-3 h-12 flex-1 rounded-2xl bg-surface px-4 text-ink" placeholder="Write a message..." placeholderTextColor="#817C94" value={text} onChangeText={setText} onSubmitEditing={submit} /><TouchableOpacity className="h-12 w-12 items-center justify-center rounded-2xl bg-brand" onPress={submit}><Text className="text-xl text-white">➤</Text></TouchableOpacity></View></KeyboardAvoidingView>;
  return <View className="flex-1 bg-canvas"><View className="px-6 pb-5 pt-6"><Text className="text-[10px] font-extrabold tracking-[2px] text-brand">CONNECT WITH YOUR COMMUNITY</Text><Text className="mt-1 text-4xl font-extrabold text-ink">Chat</Text></View><TouchableOpacity className="mx-6 mb-4 rounded-2xl bg-brand p-4" onPress={async () => { try { openChat(await getAdminChat(token)); } catch (e) { onError(e); } }}><Text className="font-extrabold text-white">Chat with Admin</Text><Text className="mt-1 text-xs text-[#e7e1ff]">Get help from the Medi team</Text></TouchableOpacity><TextInput className="mx-6 h-14 rounded-2xl border border-line bg-surface px-4 text-ink" placeholder="Search users to chat..." placeholderTextColor="#817C94" value={query} onChangeText={setQuery} /><FlatList className="mt-4 px-6" data={users} keyExtractor={item => item.id} renderItem={({ item }) => <TouchableOpacity className="flex-row items-center border-b border-line py-4" onPress={() => openChat(item)}><View className="mr-3 h-11 w-11 items-center justify-center rounded-full bg-[#EDE9FE]"><Text className="font-extrabold text-brand">{item.name?.[0]?.toUpperCase() || '?'}</Text></View><View><Text className="font-bold text-ink">{item.name || 'Medi user'}</Text><Text className="text-xs text-muted">{item.email || 'Available to chat'}</Text></View><Text className="ml-auto text-xl text-brand">›</Text></TouchableOpacity>} ListEmptyComponent={<Text className="py-10 text-center text-muted">No other users found yet.</Text>} /></View>;
}
