import { Platform, StyleSheet } from 'react-native';
import COLORS from '../theme/colors';

const styles = StyleSheet.create({
  flexOne: { flex: 1 },
  flexEnd: { justifyContent: 'flex-end' },
  container: { flex: 1, backgroundColor: COLORS.bg },
  scrollContent: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 28, paddingBottom: 40 },
  heroBand: { height: 240, overflow: 'hidden', backgroundColor: COLORS.accent, borderBottomLeftRadius: 36, borderBottomRightRadius: 36 },
  heroOrbLarge: { position: 'absolute', width: 210, height: 210, borderRadius: 105, backgroundColor: 'rgba(255,255,255,0.10)', right: -55, top: -60 },
  heroOrbSmall: { position: 'absolute', width: 150, height: 150, borderRadius: 75, backgroundColor: 'rgba(255,255,255,0.08)', left: -55, top: 78 },
  heroIdentity: { alignItems: 'center', paddingTop: 20 },
  heroLogo: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.20)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.30)' },
  heroLogoMark: { color: COLORS.white, fontSize: 23, fontWeight: '900' },
  heroTitle: { color: COLORS.white, fontSize: 24, fontWeight: '800', marginTop: 8 },
  heroSubtitle: { color: 'rgba(255,255,255,0.72)', fontSize: 12, fontWeight: '600', marginTop: 2 },
  heroTaskCard: { position: 'absolute', width: 208, bottom: 18, alignSelf: 'center', padding: 14, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.20)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)' },
  heroTaskRow: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 10 },
  heroCheck: { width: 20, height: 20, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.38)', alignItems: 'center', justifyContent: 'center' },
  heroCheckText: { color: COLORS.white, fontSize: 10, fontWeight: '800' },
  heroTaskLine: { flex: 1, height: 7, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.48)' },
  heroPill: { borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3, backgroundColor: 'rgba(254,243,199,0.72)' },
  heroPillText: { color: '#D97706', fontSize: 9, fontWeight: '700' },
  heroProgressTrack: { height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.20)', overflow: 'hidden' },
  heroProgressValue: { width: '68%', height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.72)' },
  welcomeContainer: { marginBottom: 22 },
  welcomeTitle: { color: COLORS.textPrimary, fontSize: 24, fontWeight: '800' },
  welcomeSubtitle: { color: COLORS.textMuted, fontSize: 14, marginTop: 4 },
  brandContainer: { alignItems: 'center', marginBottom: 28 },
  logoBadge: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  logoText: { fontSize: 22, fontWeight: '800', color: COLORS.white },
  brandTitle: { fontSize: 26, fontWeight: '800', color: COLORS.textPrimary, letterSpacing: 0.5 },
  brandSubtitle: { fontSize: 13, color: COLORS.textSecondary, marginTop: 6, textAlign: 'center' },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.surfaceMuted,
    borderRadius: 14,
    padding: 4,
    marginBottom: 18,
  },
  toggleBtn: { flex: 1, paddingVertical: 11, alignItems: 'center', borderRadius: 10 },
  toggleBtnActive: { backgroundColor: COLORS.white, elevation: 2 },
  toggleBtnText: { color: COLORS.textSecondary, fontSize: 13, fontWeight: '600' },
  toggleBtnTextActive: { color: COLORS.accent, fontWeight: '700' },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  errorBanner: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    color: COLORS.danger,
    fontSize: 13,
    fontWeight: '600',
    padding: 10,
    borderRadius: 10,
    marginBottom: 14,
    textAlign: 'center',
  },
  inputGroup: { marginBottom: 14 },
  inputLabel: { color: COLORS.textSecondary, fontSize: 13, fontWeight: '600', marginBottom: 6 },
  input: {
    backgroundColor: COLORS.inputBg,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: COLORS.textPrimary,
    fontSize: 14,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
  },
  phoneRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  countryCodeBadge: {
    backgroundColor: COLORS.inputBg,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
  },
  countryCodeText: { color: COLORS.textPrimary, fontSize: 14, fontWeight: '600' },
  phoneInput: { flex: 1 },
  primaryBtn: { backgroundColor: COLORS.accent, paddingVertical: 14, borderRadius: 12, alignItems: 'center', marginTop: 6 },
  btnDisabled: { opacity: 0.6 },
  primaryBtnText: { color: COLORS.white, fontSize: 15, fontWeight: '700', letterSpacing: 0.3 },
  signUpLink: { marginTop: 22, alignItems: 'center' },
  signUpLinkText: { color: COLORS.textSecondary, fontSize: 14 },
  signUpAccentText: { color: COLORS.accentLight, fontWeight: '700' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.65)', justifyContent: 'flex-end' },
  bottomSheetCard: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: 22,
    paddingBottom: Platform.OS === 'ios' ? 36 : 22,
    paddingTop: 12,
    maxHeight: '90%',
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: COLORS.cardBorder,
  },
  sheetHandle: { width: 36, height: 4, borderRadius: 2, backgroundColor: COLORS.inputBorder, alignSelf: 'center', marginBottom: 16 },
  sheetTitle: { fontSize: 22, fontWeight: '800', color: COLORS.textPrimary, marginBottom: 4 },
  sheetSubtitle: { fontSize: 13, color: COLORS.textSecondary, marginBottom: 18 },
  closeModalBtn: { marginTop: 14, marginBottom: 6, alignItems: 'center' },
  closeModalText: { color: COLORS.textSecondary, fontSize: 14 },
});

export default styles;
