import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Platform, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { getChatMessages, sendChatMessage } from '../services/api';

export default function ChatThread({ person, user, token, onBack, onError }) {
  const [messages, setMessages] = useState([]); const [text, setText] = useState(''); const [loading, setLoading] = useState(true);
  const refresh = async () => { try { setMessages((await getChatMessages(person.id, token)).messages); } catch (e) { onError(e); } finally { setLoading(false); } };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { refresh(); const id = setInterval(refresh, 5000); return () => clearInterval(id); }, [person.id, token]);
  async function submit() { const value = text.trim(); if (!value) return; setText(''); try { const message = await sendChatMessage(person.id, value, token); setMessages(items => [...items, message]); } catch (e) { setText(value); onError(e); } }
  return <KeyboardAvoidingView className="flex-1 bg-canvas" behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View className="flex-row items-center border-b border-line px-6 py-5"><TouchableOpacity onPress={onBack}><Text className="mr-4 text-2xl text-brand">‹</Text></TouchableOpacity><View><Text className="text-xl font-extrabold text-ink">{person.name}</Text><Text className="text-xs text-[#47B8A5]">{person.role === 'admin' ? 'Medi Admin' : 'Online'}</Text></View></View>{loading ? <ActivityIndicator className="mt-8" color="#6750E8" /> : <FlatList className="flex-1 px-5" data={messages} keyExtractor={item => item._id} renderItem={({ item }) => <View className={`my-1 max-w-[82%] rounded-2xl px-4 py-3 ${String(item.sender) === String(user.id) ? 'self-end bg-brand' : 'self-start border border-line bg-surface'}`}><Text className={String(item.sender) === String(user.id) ? 'text-white' : 'text-ink'}>{item.text}</Text></View>} contentContainerStyle={{ paddingVertical: 16 }} />}<View className="flex-row items-center border-t border-line bg-canvas px-4 py-3"><TextInput className="mr-3 h-12 flex-1 rounded-2xl bg-surface px-4 text-ink" placeholder="Write a message..." placeholderTextColor="#817C94" value={text} onChangeText={setText} onSubmitEditing={submit} /><TouchableOpacity className="h-12 w-12 items-center justify-center rounded-2xl bg-brand" onPress={submit}><Text className="text-xl text-white">➤</Text></TouchableOpacity></View></KeyboardAvoidingView>;
}
